"""
app.py — Flask webhook server that Twilio calls during a live call.

Endpoints:
  POST /answer          — called when the outbound call is answered
  POST /gather          — receives speech recognition results from Twilio
  POST /recording_done  — called when Twilio finishes saving the recording
"""

from __future__ import annotations

import logging
import os
import threading
from typing import Any

from flask import Flask, request, Response
from twilio.twiml.voice_response import VoiceResponse, Gather

import config
from patient_agent import PatientAgent
from transcriber import process_call
from bug_reporter import report_bugs

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)-8s %(name)s — %(message)s",
)
logger = logging.getLogger(__name__)

app = Flask(__name__)

# In-memory state: call_sid → {agent, call_number, turn}
_CALLS: dict[str, dict[str, Any]] = {}
_CALL_COUNTER = 0
_LOCK = threading.Lock()


# ── Helpers ────────────────────────────────────────────────────────────────────

def _twiml_say_and_gather(text: str, action_url: str, timeout: int = 5) -> str:
    """
    Build TwiML that:
      1. Says *text* using the OpenAI TTS audio (served as a <Play>)
      2. Records the agent's speech with a <Gather>
    """
    # We use Twilio's built-in <Say> with a decent voice.
    # Swap to <Play> pointing at a hosted MP3 (generated by tts.text_to_speech)
    # if you want OpenAI TTS quality on the call itself.
    response = VoiceResponse()

    # Start recording the whole call (once, on the first turn)
    gather = Gather(
        input="speech",
        action=action_url,
        timeout=timeout,
        speech_timeout="auto",
        language="en-US",
    )
    gather.say(text, voice="Polly.Joanna")   # AWS Polly via Twilio
    response.append(gather)

    # If Gather times out (no speech detected), post to the same action
    response.redirect(action_url)
    return str(response)


def _twiml_hangup(text: str = "") -> str:
    response = VoiceResponse()
    if text:
        response.say(text, voice="Polly.Joanna")
    response.hangup()
    return str(response)


# ── Routes ─────────────────────────────────────────────────────────────────────

@app.route("/answer", methods=["POST"])
def answer() -> Response:
    """Called when the remote party answers the call."""
    global _CALL_COUNTER

    call_sid: str = request.form.get("CallSid", "unknown")

    with _LOCK:
        _CALL_COUNTER += 1
        call_number = _CALL_COUNTER
        agent = PatientAgent(call_sid)
        _CALLS[call_sid] = {"agent": agent, "call_number": call_number, "turn": 0}

    logger.info("[%s] Call #%d answered — generating opening statement.", call_sid, call_number)

    opening = agent.opening_statement()
    action_url = f"{config.WEBHOOK_BASE_URL}/gather"

    # Recording is initiated at the call-creation level in main.py (record=True).
    # Here we just need to gather the conversation.
    response = VoiceResponse()

    gather = Gather(
        input="speech",
        action=action_url,
        timeout=6,
        speech_timeout="auto",
        language="en-US",
    )
    gather.say(opening, voice="Polly.Joanna")
    response.append(gather)
    response.redirect(action_url)

    return Response(str(response), mimetype="application/xml")


@app.route("/gather", methods=["POST"])
def gather() -> Response:
    """Called by Twilio after each speech segment from the remote agent."""
    call_sid: str = request.form.get("CallSid", "unknown")
    speech_result: str = request.form.get("SpeechResult", "")
    confidence: str = request.form.get("Confidence", "0")

    logger.info(
        "[%s] Agent said (conf=%.2f): %r",
        call_sid, float(confidence or 0), speech_result
    )

    call_state = _CALLS.get(call_sid)
    if not call_state:
        logger.warning("[%s] Unknown call — hanging up.", call_sid)
        return Response(_twiml_hangup(), mimetype="application/xml")

    agent: PatientAgent = call_state["agent"]
    call_state["turn"] += 1

    # Handle empty speech (silence / timeout)
    if not speech_result.strip():
        logger.info("[%s] Empty speech detected — prompting again.", call_sid)
        speech_result = "(silence)"

    # Generate patient reply
    patient_reply = agent.respond(speech_result)
    logger.info("[%s] Patient reply: %r", call_sid, patient_reply)

    # Check if we should end the call
    if agent.should_end_call():
        logger.info("[%s] Patient is ending the call.", call_sid)
        return Response(_twiml_hangup(patient_reply), mimetype="application/xml")

    action_url = f"{config.WEBHOOK_BASE_URL}/gather"
    twiml = _twiml_say_and_gather(patient_reply, action_url)
    return Response(twiml, mimetype="application/xml")


@app.route("/recording_done", methods=["POST"])
def recording_done() -> Response:
    """Called by Twilio when the call recording is ready."""
    call_sid: str = request.form.get("CallSid", "unknown")
    recording_sid: str = request.form.get("RecordingSid", "")
    recording_url: str = request.form.get("RecordingUrl", "")
    recording_status: str = request.form.get("RecordingStatus", "")

    logger.info(
        "[%s] Recording done — sid=%s status=%s url=%s",
        call_sid, recording_sid, recording_status, recording_url
    )

    call_state = _CALLS.get(call_sid)
    call_number = call_state["call_number"] if call_state else 0

    # Process in a background thread so we respond to Twilio immediately
    def _process() -> None:
        try:
            result = process_call(call_sid)
            transcript = result.get("transcript", "")
            if transcript:
                # Save the structured conversation transcript too
                if call_state:
                    agent: PatientAgent = call_state["agent"]
                    agent.save_transcript(
                        os.path.join(config.TRANSCRIPT_DIR, f"{call_sid}_conversation.json")
                    )
                # Bug analysis
                report_bugs(transcript, call_sid, call_number)
        except Exception:
            logger.exception("[%s] Error processing recording.", call_sid)

    threading.Thread(target=_process, daemon=True).start()

    return Response("<Response/>", mimetype="application/xml")


@app.route("/health", methods=["GET"])
def health() -> Response:
    return Response("ok", status=200)


if __name__ == "__main__":
    os.makedirs(config.AUDIO_DIR, exist_ok=True)
    os.makedirs(config.TRANSCRIPT_DIR, exist_ok=True)
    app.run(host="0.0.0.0", port=config.WEBHOOK_PORT, debug=False)
