"""
bug_reporter.py — detect and log bugs observed during calls.

Bugs are appended to BUGS.md and optionally to a machine-readable JSON log.
"""

from __future__ import annotations

import json
import logging
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import openai

import config

logger = logging.getLogger(__name__)

_client = openai.OpenAI(api_key=config.OPENAI_API_KEY)

# Machine-readable bug log
_BUG_JSON_LOG = os.path.join(config.CALLS_DIR, "bugs.json")

# ── Bug categories ─────────────────────────────────────────────────────────────
BUG_CATEGORIES = [
    "misheard_name",
    "wrong_date_time",
    "dropped_context",
    "incorrect_confirmation",
    "unexpected_silence",
    "scripted_loop",
    "invalid_information",
    "poor_error_handling",
    "missing_field_prompt",
    "other",
]

_ANALYSIS_PROMPT = """You are a QA engineer analysing a phone-call transcript between an AI
healthcare scheduling agent and a patient.

Your job: identify any bugs, errors, or poor behaviours exhibited by the AGENT (not the patient).

For each bug found, output a JSON array item like:
{{
  "category": "<one of: {categories}>",
  "severity": "<low|medium|high>",
  "turn": <turn number where the bug occurred, or null>,
  "description": "<concise description>",
  "agent_text": "<exact agent utterance that demonstrates the bug>"
}}

If no bugs are found, return an empty JSON array [].

Transcript:
{transcript}
""".format(categories=", ".join(BUG_CATEGORIES), transcript="{transcript}")


# ── Core functions ─────────────────────────────────────────────────────────────

def analyse_transcript(transcript: str, call_sid: str) -> list[dict[str, Any]]:
    """
    Use GPT-4o to detect bugs in a call transcript.
    Returns a list of bug dicts.
    """
    prompt = _ANALYSIS_PROMPT.format(transcript=transcript)

    completion = _client.chat.completions.create(
        model=config.OPENAI_CHAT_MODEL,
        messages=[{"role": "user", "content": prompt}],
        temperature=0,
        max_tokens=1024,
        response_format={"type": "json_object"},
    )
    raw = completion.choices[0].message.content or "[]"

    # The model sometimes wraps the array in {"bugs": [...]}
    try:
        parsed = json.loads(raw)
        if isinstance(parsed, list):
            bugs = parsed
        elif isinstance(parsed, dict):
            # Try common wrapper keys
            for key in ("bugs", "issues", "results", "data"):
                if key in parsed and isinstance(parsed[key], list):
                    bugs = parsed[key]
                    break
            else:
                values = list(parsed.values())
                if values and isinstance(values[0], list):
                    bugs = values[0]
                else:
                    logger.warning(
                        "[%s] Unexpected JSON structure from bug analysis — defaulting to []. "
                        "Keys: %s  Data: %.200s", call_sid, list(parsed.keys()), str(parsed)
                    )
                    bugs = []
        else:
            bugs = []
    except json.JSONDecodeError:
        logger.warning("[%s] Could not parse bug analysis JSON: %r", call_sid, raw[:200])
        bugs = []

    for bug in bugs:
        bug["call_sid"] = call_sid
        bug["detected_at"] = datetime.now(timezone.utc).isoformat()

    logger.info("[%s] Detected %d bug(s).", call_sid, len(bugs))
    return bugs


def append_to_markdown(bugs: list[dict[str, Any]], call_sid: str, call_number: int) -> None:
    """Append bug findings for a single call to BUGS.md."""
    report_path = config.BUG_REPORT_PATH
    header_needed = not Path(report_path).exists()

    with open(report_path, "a", encoding="utf-8") as fh:
        if header_needed:
            fh.write("# Bug Report — Pretty Good AI Voice Agent\n\n")
            fh.write("Auto-generated by `bug_reporter.py`.\n\n")
            fh.write("---\n\n")

        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        fh.write(f"## Call #{call_number} — SID: `{call_sid}`  _{timestamp}_\n\n")

        if not bugs:
            fh.write("No bugs detected in this call.\n\n")
        else:
            for i, bug in enumerate(bugs, 1):
                severity_badge = {"high": "🔴", "medium": "🟡", "low": "🟢"}.get(
                    bug.get("severity", "low"), "⚪"
                )
                fh.write(
                    f"### Bug {i}: {severity_badge} [{bug.get('severity','?').upper()}] "
                    f"`{bug.get('category','other')}`\n\n"
                )
                fh.write(f"**Turn:** {bug.get('turn', 'N/A')}  \n")
                fh.write(f"**Description:** {bug.get('description', '')}  \n")
                agent_text = bug.get("agent_text", "")
                if agent_text:
                    fh.write(f"**Agent said:** > {agent_text}  \n")
                fh.write("\n")

        fh.write("---\n\n")

    logger.info("Bugs appended to %s", report_path)


def append_to_json_log(bugs: list[dict[str, Any]]) -> None:
    """Append bugs to the machine-readable JSON log."""
    os.makedirs(config.CALLS_DIR, exist_ok=True)

    existing: list[dict[str, Any]] = []
    if Path(_BUG_JSON_LOG).exists():
        with open(_BUG_JSON_LOG, "r", encoding="utf-8") as fh:
            try:
                existing = json.load(fh)
            except json.JSONDecodeError:
                existing = []

    existing.extend(bugs)

    with open(_BUG_JSON_LOG, "w", encoding="utf-8") as fh:
        json.dump(existing, fh, indent=2, ensure_ascii=False)


def report_bugs(transcript: str, call_sid: str, call_number: int) -> list[dict[str, Any]]:
    """
    Full pipeline: analyse transcript → write to BUGS.md and bugs.json.
    Returns the list of bugs found.
    """
    bugs = analyse_transcript(transcript, call_sid)
    append_to_markdown(bugs, call_sid, call_number)
    append_to_json_log(bugs)
    return bugs
